<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/*
 * Skema mengacu pada DATABASE_SCHEMA.md (bagian 3). Ditulis sebagai SQL karena CHECK constraint,
 * kolom GENERATED, dan index parsial tidak tersedia di Schema Builder Laravel.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE payments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id           BIGINT       NOT NULL REFERENCES orders (id) ON DELETE RESTRICT,
    method             VARCHAR(20)  NOT NULL,
    status             VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    amount             BIGINT       NOT NULL,
    cash_received      BIGINT,                    -- khusus tunai
    change_amount      BIGINT GENERATED ALWAYS AS (cash_received - amount) STORED,
    received_by        BIGINT       REFERENCES users (id) ON DELETE SET NULL,   -- kasir penerima tunai
    provider           VARCHAR(30),               -- P1: midtrans
    provider_reference VARCHAR(100),              -- P1: transaction_id dari gateway
    provider_payload   JSONB,                     -- P1
    expires_at         TIMESTAMPTZ,
    paid_at            TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT payments_method_check CHECK (method IN ('CASH', 'QRIS', 'EWALLET', 'VIRTUAL_ACCOUNT')),
    CONSTRAINT payments_status_check CHECK (status IN ('PENDING', 'PAID', 'FAILED', 'EXPIRED', 'REFUNDED')),
    CONSTRAINT payments_amount_check CHECK (amount > 0),
    CONSTRAINT payments_cash_check   CHECK (cash_received IS NULL OR cash_received >= amount),
    CONSTRAINT payments_paid_check   CHECK (status <> 'PAID' OR paid_at IS NOT NULL)
);

CREATE UNIQUE INDEX payments_one_paid_per_order  ON payments (order_id) WHERE status = 'PAID';

CREATE UNIQUE INDEX payments_provider_ref_unique ON payments (provider, provider_reference)
    WHERE provider_reference IS NOT NULL;

CREATE INDEX payments_order_idx          ON payments (order_id);

CREATE INDEX payments_status_paid_at_idx ON payments (status, paid_at);
SQL);
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS payments CASCADE');
    }
};
