<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/*
 * Skema mengacu pada DATABASE_SCHEMA.md (bagian 3). Ditulis sebagai SQL karena CHECK constraint,
 * kolom GENERATED, dan index parsial tidak tersedia di Schema Builder Laravel.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE order_item_options (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id     BIGINT       NOT NULL REFERENCES order_items (id) ON DELETE CASCADE,
    option_id         BIGINT       REFERENCES options (id) ON DELETE SET NULL,
    option_group_name VARCHAR(100) NOT NULL,      -- snapshot nama group
    option_name       VARCHAR(100) NOT NULL,      -- snapshot nama option
    price             BIGINT       NOT NULL DEFAULT 0,   -- snapshot harga tambahan per unit option
    quantity          INT          NOT NULL DEFAULT 1,
    CONSTRAINT order_item_options_price_check    CHECK (price >= 0),
    CONSTRAINT order_item_options_quantity_check CHECK (quantity > 0)
);

CREATE INDEX order_item_options_item_idx   ON order_item_options (order_item_id);

CREATE INDEX order_item_options_option_idx ON order_item_options (option_id);
SQL);
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS order_item_options CASCADE');
    }
};
