<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/*
 * Skema mengacu pada DATABASE_SCHEMA.md (bagian 3). Ditulis sebagai SQL karena CHECK constraint,
 * kolom GENERATED, dan index parsial tidak tersedia di Schema Builder Laravel.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE products (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     BIGINT       NOT NULL REFERENCES categories (id) ON DELETE RESTRICT,
    name            VARCHAR(150) NOT NULL,
    description     TEXT,
    price           BIGINT       NOT NULL,
    image_url       VARCHAR(500),
    image_public_id VARCHAR(255),                 -- id aset di Cloudinary, untuk penghapusan gambar
    stock           INT,                          -- NULL = stok tidak dilacak
    status          VARCHAR(20)  NOT NULL DEFAULT 'AVAILABLE',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT products_price_check  CHECK (price >= 0),
    CONSTRAINT products_stock_check  CHECK (stock IS NULL OR stock >= 0),
    CONSTRAINT products_status_check CHECK (status IN ('AVAILABLE', 'UNAVAILABLE', 'SOLD_OUT'))
);

CREATE INDEX products_category_status_idx ON products (category_id, status) WHERE deleted_at IS NULL;

CREATE INDEX products_name_trgm_idx       ON products USING gin (name gin_trgm_ops);
SQL);
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS products CASCADE');
    }
};
