<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/*
 * Skema mengacu pada DATABASE_SCHEMA.md (bagian 3). Ditulis sebagai SQL karena CHECK constraint,
 * kolom GENERATED, dan index parsial tidak tersedia di Schema Builder Laravel.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE order_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT       NOT NULL REFERENCES orders (id)   ON DELETE CASCADE,
    product_id      BIGINT       NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
    product_name    VARCHAR(150) NOT NULL,        -- snapshot
    unit_price      BIGINT       NOT NULL,        -- snapshot harga dasar produk
    quantity        INT          NOT NULL,
    options_price   BIGINT       NOT NULL DEFAULT 0,   -- total harga tambahan option untuk 1 unit
    subtotal        BIGINT       NOT NULL,        -- (unit_price + options_price) * quantity
    special_request VARCHAR(250),                 -- permintaan bebas customer
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT order_items_quantity_check CHECK (quantity > 0),
    CONSTRAINT order_items_price_check    CHECK (unit_price >= 0 AND options_price >= 0),
    CONSTRAINT order_items_subtotal_check CHECK (subtotal = (unit_price + options_price) * quantity),
    CONSTRAINT order_items_request_check  CHECK (
        special_request IS NULL OR char_length(special_request) <= 250)
);

CREATE INDEX order_items_order_idx   ON order_items (order_id);

CREATE INDEX order_items_product_idx ON order_items (product_id);
SQL);
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS order_items CASCADE');
    }
};
