<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/*
 * Skema mengacu pada DATABASE_SCHEMA.md (bagian 3). Ditulis sebagai SQL karena CHECK constraint,
 * kolom GENERATED, dan index parsial tidak tersedia di Schema Builder Laravel.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE order_status_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT      NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    from_status   VARCHAR(20),                    -- NULL pada pembuatan order
    to_status     VARCHAR(20) NOT NULL,
    changed_by_id BIGINT      REFERENCES users (id) ON DELETE SET NULL,   -- NULL = sistem/webhook
    reason        TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX order_status_logs_order_idx ON order_status_logs (order_id, created_at);
SQL);
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS order_status_logs CASCADE');
    }
};
