<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/*
 * Skema mengacu pada DATABASE_SCHEMA.md (bagian 3). Ditulis sebagai SQL karena CHECK constraint,
 * kolom GENERATED, dan index parsial tidak tersedia di Schema Builder Laravel.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE orders (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number            VARCHAR(30)  NOT NULL,                   -- contoh: CF-20261004-001
    daily_number            INT          NOT NULL,                   -- tampil di Kitchen: #001
    user_id                 BIGINT       REFERENCES users (id) ON DELETE RESTRICT,   -- NULL = walk-in
    created_by_id           BIGINT       NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    source                  VARCHAR(20)  NOT NULL,
    customer_name           VARCHAR(100),                            -- opsional untuk walk-in
    order_type              VARCHAR(20)  NOT NULL,
    table_number            VARCHAR(10),
    status                  VARCHAR(20)  NOT NULL DEFAULT 'PENDING_PAYMENT',

    subtotal                BIGINT       NOT NULL,
    discount_amount         BIGINT       NOT NULL DEFAULT 0,
    tax_percent             NUMERIC(5,2) NOT NULL DEFAULT 0,
    tax_amount              BIGINT       NOT NULL DEFAULT 0,
    service_charge_percent  NUMERIC(5,2) NOT NULL DEFAULT 0,
    service_charge_amount   BIGINT       NOT NULL DEFAULT 0,
    total                   BIGINT       NOT NULL,

    promotion_id            BIGINT,                                  -- FK ditambahkan di migrasi P1
    promotion_code          VARCHAR(50),                             -- snapshot kode promo
    idempotency_key         VARCHAR(64),

    confirmed_at            TIMESTAMPTZ,
    preparing_at            TIMESTAMPTZ,
    ready_at                TIMESTAMPTZ,
    completed_at            TIMESTAMPTZ,
    cancelled_at            TIMESTAMPTZ,
    cancelled_by_id         BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    cancel_reason           TEXT,

    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT orders_number_unique     UNIQUE (order_number),
    CONSTRAINT orders_source_check      CHECK (source IN ('customer', 'cashier')),
    CONSTRAINT orders_type_check        CHECK (order_type IN ('DINE_IN', 'TAKE_AWAY')),
    CONSTRAINT orders_status_check      CHECK (status IN (
        'PENDING_PAYMENT', 'PAID', 'CONFIRMED', 'PREPARING', 'READY', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT orders_dine_in_table     CHECK (order_type <> 'DINE_IN' OR table_number IS NOT NULL),
    CONSTRAINT orders_customer_has_user CHECK (source <> 'customer' OR user_id IS NOT NULL),
    CONSTRAINT orders_amounts_check     CHECK (
        subtotal >= 0 AND discount_amount >= 0 AND tax_amount >= 0
        AND service_charge_amount >= 0 AND total >= 0
        AND discount_amount <= subtotal),
    CONSTRAINT orders_total_check       CHECK (
        total = subtotal - discount_amount + tax_amount + service_charge_amount),
    CONSTRAINT orders_cancel_check      CHECK (status <> 'CANCELLED' OR cancelled_at IS NOT NULL)
);

CREATE UNIQUE INDEX orders_idempotency_unique
    ON orders (created_by_id, idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE INDEX orders_user_created_idx    ON orders (user_id, created_at DESC);

CREATE INDEX orders_status_created_idx  ON orders (status, created_at);

CREATE INDEX orders_created_at_idx      ON orders (created_at);

CREATE INDEX orders_kitchen_queue_idx   ON orders (confirmed_at)
    WHERE status IN ('CONFIRMED', 'PREPARING', 'READY');
SQL);
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS orders CASCADE');
    }
};
