<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/*
 * Skema mengacu pada DATABASE_SCHEMA.md (bagian 3). Ditulis sebagai SQL karena CHECK constraint,
 * kolom GENERATED, dan index parsial tidak tersedia di Schema Builder Laravel.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE options (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_group_id BIGINT       NOT NULL REFERENCES option_groups (id) ON DELETE RESTRICT,
    name            VARCHAR(100) NOT NULL,        -- contoh: Less Sugar, Oat Milk, Extra Shot
    price           BIGINT       NOT NULL DEFAULT 0,   -- harga tambahan, 0 = gratis
    is_available    BOOLEAN      NOT NULL DEFAULT TRUE,
    is_default      BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order      INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT options_price_check CHECK (price >= 0)
);

CREATE UNIQUE INDEX options_group_name_unique
    ON options (option_group_id, lower(name)) WHERE deleted_at IS NULL;

CREATE INDEX options_group_sort_idx
    ON options (option_group_id, sort_order) WHERE deleted_at IS NULL;
SQL);
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS options CASCADE');
    }
};
